services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5459:8080'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npx http-server dist/angularDragAndDrop/browser -p 8080 -a 0.0.0.0"
